CREATE TABLE 
	[dbo].Dim_Calendario
	(
		TMPO_ID_TEMPO							INT NOT NULL
		,TMPO_DT_DATA							DATETIME2(7)		-- 20140401
		,TMPO_DS_DATA							VARCHAR(10)		-- 01/01/2014
		
		,TMPO_CD_DIA_SEMANA						INT				-- 20140414
		,TMPO_DS_DIA_SEMANA						VARCHAR(15)		-- 1ª Quarta
		,TMPO_NR_DIA_SEMANA						INT				-- 1 = Domingo - 2 - Segunda - 3 terça 
		--,TMPO_CD_SEMANA_MES						INT				-- 20140101
		--,TMPO_DS_SEMANA_MES						VARCHAR(20)		-- 1ª Semana Jan/2014
		--,TMPO_DS_SEMANA_MES_ANO					VARCHAR(20)		-- 01/01-05/01 de 2014 -- Caso seja de 2ª a Domingo 
		--,TMPO_CD_DIA_SEMANA_ANO_CALENDARIO		INT				-- 201401
		--,TMPO_DS_DIA_SEMANA_ANO_CALENDARIO		VARCHAR(15)		-- 1ª Semana/2014
		--,TMPO_CD_DIA_SEMANA_ANO_FISCAL			INT				-- 201327
		--,TMPO_DS_DIA_SEMANA_ANO_FISCAL			VARCHAR(15)		-- 27ª Semana/2013
		,TMPO_CD_DIA_UTIL						INT				-- 1 Dia Util - 0 Feriado ou Fim de Semana, idS dos Feriados do Pais
		,TMPO_DS_DIA_UTIL						VARCHAR(50)		-- Dia Útil, Fim de Semana, Páscoa, Natal...
		
		,TMPO_CD_FERIADO						INT				-- 1 - Ano Novo - 2 - Carnaval
		,TMPO_DS_FERIADO						VARCHAR(50)		-- Ano Novo,Carnaval
		,TMPO_CD_MES_CALENDARIO					INT				-- 201401
		,TMPO_DS_MES_CALENDARIO					VARCHAR(15)		-- Jan/2014

		,TMPO_CD_MESNUM_CALENDARIO					INT				-- 201401
		,TMPO_DS_MESNUM_CALENDARIO					VARCHAR(15)		-- 01/14

		,TMPO_CD_BIMESTRE_CALENDARIO			INT				-- 201401
		,TMPO_DS_BIMESTRE_CALENDARIO			VARCHAR(20)		-- 1ºBim/2014
		,TMPO_CD_TRIMESTRE_CALENDARIO			INT				-- 201401
		,TMPO_DS_TRIMESTRE_CALENDARIO			VARCHAR(20)		-- 1ºTri/2014
	
		,TMPO_CD_SEMESTRE_CALENDARIO			INT				-- 201401
		,TMPO_DS_SEMESTRE_CALENDARIO			VARCHAR(25)		-- 1ºSem/2014
		,TMPO_CD_ANO_CALENDARIO					INT				-- 2014
		,TMPO_DS_ANO_CALENDARIO					VARCHAR(10)		-- Ano/2014
		,CONSTRAINT PK_DIM_0003_IDC_001 PRIMARY KEY CLUSTERED (TMPO_ID_TEMPO)
		,INDEX IX_DIM_0003_IDX_002 NONCLUSTERED (TMPO_DT_DATA)
	)

GO
